;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
         counsel-M-x
         evil-backward-char
         evil-digit-argument-or-evil-org-beginning-of-line
         evil-exit-visual-state
         evil-forward-char
         evil-insert
         evil-next-line
         evil-normal-state
         evil-previous-line
         isearch-exit
         ))

(setq mc/cmds-to-run-once
      '(
         evil-delete
         evil-force-normal-state
         evil-org-append-line
         evil-org-delete
         evil-repeat-pop
         evil-search-forward
         iedit-switch-to-mc-mode
         isearch-printing-char
         org-self-insert-command
         ))
