;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
         evil-force-normal-state
         evil-next-line
         evil-previous-line
         ))

(setq mc/cmds-to-run-once
      '(
         iedit-switch-to-mc-mode
         org-date-from-calendar
         ))
